export const PRODUCTS = [
  {
    slug: 'ihotel',
    name: 'iHotel',
    image: 'https://source.unsplash.com/400x300/?hotel',
    icon: '🏨',
    color: '#2563EB',
    textColor: 'text-blue-500',
    bgFrom: 'from-blue-600',
    bgTo: 'to-blue-800',
    borderColor: 'border-blue-500/30',
    tagline: 'Smart Hospitality, Redefined',
    shortDesc: 'Complete IoT platform for hotels, resorts, and BnBs — from room automation to guest experience management.',
    description: 'iHotel transforms any accommodation into a smart, connected property. Control lighting, AC, curtains, and door locks from a unified dashboard. Monitor energy consumption in real time, manage reservations via a built-in PMS, and let guests control their own room via a QR-code-linked self-service portal.',
    features: [
      'Room automation — lights, AC, curtains, blinds, door lock',
      'Live occupancy heatmap across all floors',
      'Built-in PMS: reservations, check-in, check-out',
      'Guest self-service portal via QR code link',
      'SOS, Make-Up-Room, Do-Not-Disturb service system',
      'Power-down mode for unoccupied rooms',
      'Real-time telemetry: temperature, humidity, CO₂, motion',
      'Staff shift management & audit logs',
    ],
    stats: [
      { value: '40%', label: 'Energy Savings' },
      { value: '60%', label: 'Faster Service' },
      { value: '100%', label: 'Real-Time Visibility' },
      { value: '24/7', label: 'Remote Monitoring' },
    ],
    useCases: ['5-star hotels', 'Budget hotel chains', 'Serviced apartments', 'BnB & boutique stays'],
    industries: ['Hospitality', 'Real Estate', 'Tourism'],
  },
  {
    slug: 'ibms',
    name: 'iBMS',
    image: 'https://source.unsplash.com/400x300/?office-building',
    icon: '🏢',
    color: '#059669',
    textColor: 'text-emerald-500',
    bgFrom: 'from-emerald-600',
    bgTo: 'to-emerald-800',
    borderColor: 'border-emerald-500/30',
    tagline: 'Intelligent Buildings, Optimised Operations',
    shortDesc: 'Building Management System for commercial spaces, malls, government buildings, and campuses.',
    description: 'iBMS delivers centralised control over every building system — HVAC, lighting, access control, energy metering, and elevator monitoring — from a single intelligent dashboard. Designed for facility managers who demand maximum uptime with minimum operational cost.',
    features: [
      'HVAC centralised control & scheduling',
      'Energy metering per zone, floor & tenant',
      'Access control & visitor management',
      'Elevator & escalator health monitoring',
      'Predictive maintenance alerts',
      'Space utilisation & occupancy analytics',
      'Fire & safety system integration',
      'Multi-building campus management',
    ],
    stats: [
      { value: '35%', label: 'Energy Cost Savings' },
      { value: '50%', label: 'Maintenance Cost Reduction' },
      { value: '99.5%', label: 'System Uptime' },
      { value: '15 min', label: 'Avg. Fault Response' },
    ],
    useCases: ['Shopping malls', 'Government ministries', 'Corporate campuses', 'Universities', 'Airports'],
    industries: ['Commercial Real Estate', 'Government', 'Education', 'Retail'],
  },
  {
    slug: 'ifactory',
    name: 'iFactory',
    image: 'https://source.unsplash.com/400x300/?factory',
    icon: '🏭',
    color: '#D97706',
    textColor: 'text-amber-500',
    bgFrom: 'from-amber-600',
    bgTo: 'to-amber-800',
    borderColor: 'border-amber-500/30',
    tagline: 'Industrial Intelligence at Scale',
    shortDesc: 'IoT platform for manufacturing, quality control, predictive maintenance, and industrial BMS.',
    description: 'iFactory connects every machine, sensor, and production line into one intelligent industrial ecosystem. Detect anomalies before they become failures, track quality in real time, and optimise throughput with actionable AI-driven insights — all while maintaining full safety and compliance oversight.',
    features: [
      'Predictive maintenance with 85%+ anomaly accuracy',
      'Real-time machine health & vibration monitoring',
      'Production line OEE & throughput tracking',
      'Quality control defect detection & reporting',
      'Energy & utility consumption per asset',
      'Worker safety & environmental monitoring (gas, dust, temp)',
      'CMMS & ERP system integration',
      'Edge computing for sub-second response',
    ],
    stats: [
      { value: '30–50%', label: 'Downtime Reduction' },
      { value: '20–40%', label: 'Maintenance Cost Savings' },
      { value: '85%+', label: 'Anomaly Detection Accuracy' },
      { value: '2.5×', label: 'Production Efficiency' },
    ],
    useCases: ['Automotive manufacturing', 'Food & beverage', 'Pharmaceutical production', 'Oil & gas refineries', 'Electronics fabrication'],
    industries: ['Manufacturing', 'Industrial', 'Oil & Gas', 'Pharmaceutical'],
  },
  {
    slug: 'iagrix',
    name: 'iAgrix',
    image: 'https://source.unsplash.com/400x300/?agriculture',
    icon: '🌱',
    color: '#16A34A',
    textColor: 'text-green-500',
    bgFrom: 'from-green-600',
    bgTo: 'to-green-800',
    borderColor: 'border-green-500/30',
    tagline: 'Precision Agriculture, Smarter Harvests',
    shortDesc: 'IoT platform for soil monitoring, smart irrigation, crop automation, and agricultural AI insights.',
    description: 'iAgrix brings precision agriculture to every farm — from vast open fields to climate-controlled greenhouses. Monitor soil moisture, temperature, electrical conductivity, and pH in real time. Automate irrigation per crop type, cut water consumption significantly, and receive AI-powered recommendations tailored to each crop to maximise yield.',
    features: [
      'Soil parameter monitoring: moisture, temp, EC, pH, NPK',
      'Automated drip & sprinkler irrigation control',
      'Crop-type-specific watering schedules & recommendations',
      'Water consumption analytics & savings dashboard',
      'Weather station integration & forecast-based irrigation',
      'Greenhouse climate control (temp, humidity, CO₂)',
      'Yield prediction & harvest planning reports',
      'Remote farm management via mobile app',
    ],
    stats: [
      { value: '45%', label: 'Water Savings' },
      { value: '30%', label: 'Yield Increase' },
      { value: '60%', label: 'Labour Cost Reduction' },
      { value: 'Real-time', label: 'Soil & Climate Data' },
    ],
    useCases: ['Open-field crop farms', 'Greenhouses', 'Orchards & vineyards', 'Vertical farms', 'Government food-security projects'],
    industries: ['Agriculture', 'Food Production', 'Government'],
  },
  {
    slug: 'irtls',
    name: 'iRTLS',
    image: 'https://source.unsplash.com/400x300/?logistics',
    icon: '🚛',
    color: '#7C3AED',
    textColor: 'text-violet-500',
    bgFrom: 'from-violet-600',
    bgTo: 'to-violet-800',
    borderColor: 'border-violet-500/30',
    tagline: 'Track Everything. Miss Nothing.',
    shortDesc: 'Real-time logistics platform for fleet management, cold chain monitoring, goods tracking, and route intelligence.',
    description: 'iRTLS delivers complete supply chain visibility from warehouse to last mile. Track trucks, containers, and high-value goods using GPS, BLE, RFID, and UWB. Monitor temperature throughout cold chains, optimise delivery routes, and receive instant alerts for deviations, tampering, or unexpected delays.',
    features: [
      'Multi-technology: GPS + BLE + RFID + UWB',
      'Cold chain temperature monitoring & breach alerts',
      'Geofencing & route deviation notifications',
      'Fleet fuel efficiency & idling analytics',
      'Container and pallet-level asset tracking',
      '50,000+ simultaneous tracked objects per deployment',
      'ERP & WMS integration',
      'Driver behaviour & safety scoring',
    ],
    stats: [
      { value: '<1s', label: 'Location Update Latency' },
      { value: '50K+', label: 'Tracked Objects / Deployment' },
      { value: '25%', label: 'Fuel Cost Reduction' },
      { value: '99.9%', label: 'Tracking Uptime' },
    ],
    useCases: ['Pharmaceutical cold chain', 'Food & beverage distribution', 'Retail logistics', 'Port & container yards', 'Government fleet management'],
    industries: ['Logistics', 'Supply Chain', 'Retail', 'Pharmaceutical', 'Government'],
  },
  {
    slug: 'imedical',
    name: 'iMedical',
    image: 'https://source.unsplash.com/400x300/?hospital',
    icon: '🏥',
    color: '#DC2626',
    textColor: 'text-red-500',
    bgFrom: 'from-red-600',
    bgTo: 'to-red-800',
    borderColor: 'border-red-500/30',
    tagline: 'Connected Healthcare, Safer Outcomes',
    shortDesc: 'Healthcare IoT platform for patient monitoring, medical asset tracking, and hospital operations management.',
    description: 'iMedical connects patients, clinical staff, and medical assets across the hospital ecosystem. Track critical equipment in seconds with indoor RTLS, monitor patient vitals remotely, automate clinical workflows, and ensure full regulatory compliance — all from a unified clinical operations dashboard.',
    features: [
      'Indoor RTLS: real-time location of staff, patients & equipment',
      'Remote patient vital signs monitoring',
      'Medical equipment lifecycle & preventive maintenance',
      'Medication refrigerator & cold storage monitoring',
      'Nurse call & emergency response system integration',
      'Hand hygiene compliance tracking',
      'EMR & HIS integration',
      'HIPAA / PDPL-compliant data security',
    ],
    stats: [
      { value: '70%', label: 'Asset Search Time Reduction' },
      { value: '40%', label: 'Equipment Utilisation Increase' },
      { value: '<30s', label: 'Emergency Alert Response' },
      { value: '100%', label: 'Compliance Traceability' },
    ],
    useCases: ['General hospitals', 'Specialty clinics', 'Rehabilitation centres', 'Elderly care homes', 'Emergency departments'],
    industries: ['Healthcare', 'Pharmaceuticals', 'Elderly Care'],
  },
];

export function getProduct(slug) {
  return PRODUCTS.find(p => p.slug === slug);
}
